### ISSUE TITLE
Swiping sensitivity is too low

### ISSUE THREAD

**Issue by elliehl** [clam119/find-and-dine-frontend#10]
Swiping a restaurant card often doesn't work when swiping from anywhere other than the edge of the screen. Please could the sensitivity be adjusted

**Comment by Antony-Lester** [comment]
From testing on a physical device:
Swipe detection is good, But I agree that the swiping distance should be reduced.
I have implemented this & is awaiting approval.  @clam119

**Comment by clam119** [comment]
Looks good and feels good functionally, happy to close!  @elliehl

**Comment by elliehl** [comment]
Swipe distance reduction was a great improvement!
