### ISSUE TITLE
Render Error

### ISSUE THREAD

**Issue by Antony-Lester** [clam119/find-and-dine-frontend#53]
undefined is not an object (props.item.imageUrls[0])

ListTemplate.tsx Line 29

**Comment by Antony-Lester** [comment]
this is repeatable on an empty interested list, at this stage is this intended, can we add a conditional check/default?

**Comment by KirilsKnazevs** [comment]
Thank you for inform, it is all sorted!

**Comment by KirilsKnazevs** [comment]
On it!

**Comment by Antony-Lester** [comment]
have we made progress on this @KirilsKnazevs

**Comment by jlinford84** [comment]
Nothing to see here

**Comment by NikitaSelanko** [comment]
Still not resolved @KirilsKnazevs

**Comment by clam119** [comment]
@KirilsKnazevs Russian
